pr:
  branches:
    include:
    - '*'
trigger:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    if [ -z "$(system.pullRequest.sourceRepositoryUri)" ] 
    then 
      python3 runTest.py \
        --config "blessedImageConfig-temp.json" \
        --code $(SecretCode)
    else
      python3 runTest.py \
        --config "blessedImageConfig-temp.json" \
        --code $(SecretCode) \
        --pullRepo $(system.pullRequest.sourceRepositoryUri) \
        --pullId $(system.pullRequest.pullRequestNumber)
    fi
  timeoutInMinutes: 180
  displayName: 'Running test'
